### ISSUE TITLE
서버 주소 프록시 이슈

### ISSUE THREAD

**Issue by olive-su** [GongAnts/GongAnts_Untact_Study_Room#28]
## Related PR
#27 

<br>

## Content
https://github.com/GongAnts/GongAnts_Untact_Study_Room/pull/27/commits/a7f38936ca084665ea09a9f59c3a924acf364f73

- 이전에 Calendar 에서 발생하던 `react/icons` Conflicts 는 해결됐는데 이거 환경변수로 지정해주면 target을 읽어오지를 못하고 있어용..😭

<br>

- *➕ 에러 코드 스니펫*
  ```bash
  > gong_ants@2.0.0 start
  > craco start
  
  craco:  *** Cannot find ESLint loader (eslint-loader). ***
  [HPM] Missing "target" option. Example: {target: "http://www.example.org"}
  ``` 
- 이전처럼 localhost 로 하드코딩 해주면 잘 돌아가,,! 이거 node 자체에서 env 설정 해줘야하는 거얌,,???🥲

**Comment by seulg2027** [comment]
`client` 폴더 바로 아래에 .env파일 추가해쥬ㅠㅠㅠㅠ으악 깜빡스....
REACT_APP_BASIC_SERVER_URL=http://localhost:4000
요거 그냥 바로 넣으면 된다!!
